### ISSUE TITLE
Exporting Home Assistant Configuration failed

### ISSUE THREAD

**Issue by gesslinger** [grimmpp/enocean-device-manager#35]
hi @grimmpp 

just tried out your device discovery which worked fine so far. But when I try to export to home assistant I get the following error:

> Exporting Home Assistant Configuration failed!  sender id '0A' of device 'FF-9D-04-8A' is no valid number between 1 and 127.

Then I thought I could uncheck "Export to HA Config" in the right detail panel, but this had no effect.
Am I doing something wrong? Could you please check? I am using the latest version, 0.1.27.

Thanks!

**Comment by grimmpp** [comment]
Can you sende me the configure snippet of that device?

**Comment by grimmpp** [comment]
Hello @gesslinger,

this tool is still a big construction site 🙈. Sorry for that. You need to apply the change. Either push the button or enter when focus in on one of the widgets at the right. The button may be hidden because the layout was not yet properly designed. You can make the console window smaller to see the button.

![image](https://github.com/user-attachments/assets/86335240-6867-489b-bf2b-5809a5fd87be)

**Comment by gesslinger** [comment]
@grimmpp ok, thanks for the hint. With adapting the UI I can unset the "Export to HA Config". But still I cannot export in the device manager.

I had initially just readout the configuration of a FAM14 and wanted to import that to HA.

So don't know which `snippet` I could export. Here  a screenshot of one device.
![image](https://github.com/user-attachments/assets/6324c8d8-99c5-42ec-997d-c0791c532449)

**Comment by grimmpp** [comment]
Sorry, it took a bit to understand be issue. I've fixed it and made a new release v0.1.29
Please, let me know if it is working for you.

**Comment by pa-bs** [comment]
Maybe it has something todo with that topic:
With current version the HA export still fails for me:

Invalid literal for int() with base 16: 00-00-B0-01

![355977887-c70f06f9-df1d-4c04-a043-9a6eb0b9d1dc](https://github.com/user-attachments/assets/cacc22cb-d29a-4841-a1aa-aa20b0f8bc37)

**Comment by grimmpp** [comment]
Hello @pa-bs,

I've remove a bug in the export method. Maybe your problem is solved too. Can you please test v0.1.30?

**Comment by pa-bs** [comment]
Hi @grimmpp, still failing in line 53 of ha_config_generator.py in 1.30.
I simply replaced the dashes with nothing before, than it works for me.

**Comment by pa-bs** [comment]
Got it. Missed to press write to devices with attached USB300 again. Thanks!
Most of the lights and 4/13 of the covers are working now from HA. I will check the ids at the weekend.

**Comment by gesslinger** [comment]
hi @grimmpp , I could retest with v0.1.33 and the export is working now smoothly with my configuration.
Thank you very much!
